if(EXISTS "/home/dhana-inc5839/zephyrproject/zephyr_hce_task/hce_drivers/uart_build/spi_test[1]_tests.cmake")
  include("/home/dhana-inc5839/zephyrproject/zephyr_hce_task/hce_drivers/uart_build/spi_test[1]_tests.cmake")
else()
  add_test(spi_test_NOT_BUILT spi_test_NOT_BUILT)
endif()
