# prj_crc_loopback.conf
CONFIG_UART_INTERRUPT_DRIVEN=y

# Disable logging completely to avoid buffer hangs
CONFIG_LOG=n

# Don't use UART as the Zephyr console
CONFIG_UART_CONSOLE=n

CONFIG_CRC_LOOPBACK_MODE=y

# Speed optimizations for high baudrate UART
CONFIG_SPEED_OPTIMIZATIONS=y
CONFIG_ASSERT=n
